<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerX4UFfKn\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerX4UFfKn/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerX4UFfKn.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerX4UFfKn\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerX4UFfKn\App_KernelDevDebugContainer([
    'container.build_hash' => 'X4UFfKn',
    'container.build_id' => 'b9ad1907',
    'container.build_time' => 1724259798,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerX4UFfKn');
